<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Iuran_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get iuran by kode_iuran
     */
    function get_iuran($kode_iuran)
    {
        return $this->db->get_where('iuran',array('kode_iuran'=>$kode_iuran))->row_array();
    }
        
    /*
     * Get all iuran
     */
    function get_all_iuran()
    {
        $this->db->order_by('kode_iuran', 'desc');
        return $this->db->get('iuran')->result_array();
    }
        
     function result_getall(){

    $this->db->select('*');
    $this->db->from('anggotaku');
    $this->db->join('iuran', 'iuran.id_anggota = anggotaku.id_anggota'); 
    $query = $this->db->get();
    return $query->result();

    }
}
