<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class M_anggota extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get anggotum by id_anggota
     */
    function get_anggotum($id_anggota)
    {
        return $this->db->get_where('anggotaku',array('id_anggota'=>$id_anggota))->row_array();
    }
        
    /*
     * Get all anggota
     */
    function get_all_anggota()
    {
        $this->db->order_by('id_anggota', 'desc');
        return $this->db->get('anggotaku')->result_array();
    }
        
   
}
