<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class M_jadwal extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get iuran by kode_iuran
     */
    function get_iuran($id_jadwal)
    {
        return $this->db->get_where('jadwal_latihan',array('id_jadwal'=>$id_jadwal))->row_array();
    }
        
    /*
     * Get all iuran
     */
    function get_all_iuran()
    {
        $this->db->order_by('id_jadwal', 'desc');
        return $this->db->get('jadwal_latihan')->result_array();
    }
        
     function result_getall(){

    $this->db->select('*');
    $this->db->from('jadwal_latihan');
     
    $query = $this->db->get();
    return $query->result();

    }
}
